export const list = {
  name: 'native-l1',
  timestamp: '2023-10-17T00:00:00.000Z',
  version: { major: 1, minor: 0, patch: 0 },
  keywords: ['Native'],
  tokens: [
    { chain: 'AVAX', identifier: 'AVAX.AVAX', decimals: 18 },
    { chain: 'ARB', identifier: 'ARB.ETH', decimals: 18 },
    { chain: 'BASE', identifier: 'BASE.ETH', decimals: 18 },
    { chain: 'BCH', identifier: 'BCH.BCH', decimals: 8 },
    { chain: 'BNB', identifier: 'BNB.BNB', decimals: 8 },
    { chain: 'BSC', identifier: 'BSC.BNB', decimals: 18 },
    { chain: 'BTC', identifier: 'BTC.BTC', decimals: 8 },
    { chain: 'DOGE', identifier: 'DOGE.DOGE', decimals: 8 },
    { chain: 'ETH', identifier: 'ETH.ETH', decimals: 18 },
    { chain: 'XRP', identifier: 'XRP.XRP', decimals: 8 },
    { chain: 'GAIA', identifier: 'GAIA.ATOM', decimals: 6 },
    { chain: 'LTC', identifier: 'LTC.LTC', decimals: 8 },
    { chain: 'ZEC', identifier: 'ZEC.ZEC', decimals: 8 },
    { chain: 'THOR', identifier: 'THOR.RUNE', decimals: 8 },
    { chain: 'MAYA', identifier: 'MAYA.CACAO', decimals: 10 },
  ],
  count: 15,
  logo: 'https://static.thorswap.net/logo.png',
} as const;
